name: "setup"
description: "setup environment for s3s"
runs:
  using: "composite"
  steps:
    - uses: taiki-e/install-action@just
    - uses: astral-sh/setup-uv@v7
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
