[package]
name = "s3s-multipart"
version = "0.16.0-alpha.1"
description = "Async streaming parser for multipart/form-data"
readme = "../../README.md"
keywords = ["multipart", "form-data", "parser", "streaming"]
categories = ["web-programming", "asynchronous"]
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
