//! Auto generated by `s3s_codegen::v1::mcp::codegen`

#![allow(clippy::too_many_lines)]
#![allow(clippy::needless_pass_by_value)]

use std::sync::Arc;

use s3s::S3;
use s3s::dto::*;
use s3s::S3Request;

use rmcp::model::Tool;
use rmcp::model::CallToolResult;
use rmcp::model::Content;
use rmcp::model::JsonObject;

fn empty_object_schema() -> Arc<JsonObject> {
    let mut map = JsonObject::new();
    map.insert("type".to_owned(), serde_json::Value::String("object".to_owned()));
    Arc::new(map)
}

fn new_request<T>(input: T) -> S3Request<T> {
    S3Request {
        input,
        method: http::Method::GET,
        uri: http::Uri::default(),
        headers: http::HeaderMap::new(),
        extensions: http::Extensions::new(),
        credentials: None,
        region: None,
        service: None,
        trailing_headers: None,
    }
}

pub fn tool_definitions() -> Vec<Tool> {
let schema = empty_object_schema();
vec![
Tool::new("abort_multipart_upload", "This operation aborts a multipart upload. After a multipart upload is aborted, no additional parts can be uploaded using that upload ID. The storage consumed by any previously uploaded parts will b...", Arc::clone(&schema)),
Tool::new("complete_multipart_upload", "Completes a multipart upload by assembling previously uploaded parts. You first initiate the multipart upload and then upload all parts using the UploadPart operation or the UploadPartCopy operatio...", Arc::clone(&schema)),
Tool::new("copy_object", "Creates a copy of an object that is already stored in Amazon S3. You can store individual objects of up to 5 TB in Amazon S3. You create a copy of your object up to 5 GB in size in a single atomic ...", Arc::clone(&schema)),
Tool::new("create_bucket", "This action creates an Amazon S3 bucket. To create an Amazon S3 on Outposts bucket, see CreateBucket . Creates a new S3 bucket. To create a bucket, you must set up Amazon S3 and have a valid Amazon...", Arc::clone(&schema)),
Tool::new("create_bucket_metadata_table_configuration", "Creates a metadata table configuration for a general purpose bucket. For more information, see Accelerating data discovery with S3 Metadata in the Amazon S3 User Guide. Permissions To use this oper...", Arc::clone(&schema)),
Tool::new("create_multipart_upload", "This action initiates a multipart upload and returns an upload ID. This upload ID is used to associate all of the parts in the specific multipart upload. You specify this upload ID in each of your ...", Arc::clone(&schema)),
Tool::new("delete_bucket", "Deletes the S3 bucket. All objects (including all object versions and delete markers) in the bucket must be deleted before the bucket itself can be deleted. Directory buckets - If multipart uploads...", Arc::clone(&schema)),
Tool::new("delete_bucket_analytics_configuration", "This operation is not supported for directory buckets. Deletes an analytics configuration for the bucket (specified by the analytics configuration ID). To use this operation, you must have permissi...", Arc::clone(&schema)),
Tool::new("delete_bucket_cors", "This operation is not supported for directory buckets. Deletes the cors configuration information set for the bucket. To use this operation, you must have permission to perform the s3:PutBucketCORS...", Arc::clone(&schema)),
Tool::new("delete_bucket_encryption", "This implementation of the DELETE action resets the default encryption for the bucket as server-side encryption with Amazon S3 managed keys (SSE-S3). General purpose buckets - For information about...", Arc::clone(&schema)),
Tool::new("delete_bucket_intelligent_tiering_configuration", "This operation is not supported for directory buckets. Deletes the S3 Intelligent-Tiering configuration from the specified bucket. The S3 Intelligent-Tiering storage class is designed to optimize s...", Arc::clone(&schema)),
Tool::new("delete_bucket_inventory_configuration", "This operation is not supported for directory buckets. Deletes an inventory configuration (identified by the inventory ID) from the bucket. To use this operation, you must have permissions to perfo...", Arc::clone(&schema)),
Tool::new("delete_bucket_lifecycle", "Deletes the lifecycle configuration from the specified bucket. Amazon S3 removes all the lifecycle configuration rules in the lifecycle subresource associated with the bucket. Your objects never ex...", Arc::clone(&schema)),
Tool::new("delete_bucket_metadata_table_configuration", "Deletes a metadata table configuration from a general purpose bucket. For more information, see Accelerating data discovery with S3 Metadata in the Amazon S3 User Guide. Permissions To use this ope...", Arc::clone(&schema)),
Tool::new("delete_bucket_metrics_configuration", "This operation is not supported for directory buckets. Deletes a metrics configuration for the Amazon CloudWatch request metrics (specified by the metrics configuration ID) from the bucket. Note th...", Arc::clone(&schema)),
Tool::new("delete_bucket_ownership_controls", "This operation is not supported for directory buckets. Removes OwnershipControls for an Amazon S3 bucket. To use this operation, you must have the s3:PutBucketOwnershipControls permission. For more...", Arc::clone(&schema)),
Tool::new("delete_bucket_policy", "Deletes the policy of a specified bucket. Directory buckets - For directory buckets, you must make requests for this API operation to the Regional endpoint. These endpoints support path-style reque...", Arc::clone(&schema)),
Tool::new("delete_bucket_replication", "This operation is not supported for directory buckets. Deletes the replication configuration from the bucket. To use this operation, you must have permissions to perform the s3:PutReplicationConfig...", Arc::clone(&schema)),
Tool::new("delete_bucket_tagging", "This operation is not supported for directory buckets. Deletes the tags from the bucket. To use this operation, you must have permission to perform the s3:PutBucketTagging action. By default, the b...", Arc::clone(&schema)),
Tool::new("delete_bucket_website", "This operation is not supported for directory buckets. This action removes the website configuration for a bucket. Amazon S3 returns a 200 OK response upon successfully deleting a website configura...", Arc::clone(&schema)),
Tool::new("delete_object", "Removes an object from a bucket. The behavior depends on the bucket's versioning state: If bucket versioning is not enabled, the operation permanently deletes the object. If bucket versioning is en...", Arc::clone(&schema)),
Tool::new("delete_object_tagging", "This operation is not supported for directory buckets. Removes the entire tag set from the specified object. For more information about managing object tags, see Object Tagging. To use this operati...", Arc::clone(&schema)),
Tool::new("delete_objects", "This operation enables you to delete multiple objects from a bucket using a single HTTP request. If you know the object keys that you want to delete, then this operation provides a suitable alterna...", Arc::clone(&schema)),
Tool::new("delete_public_access_block", "This operation is not supported for directory buckets. Removes the PublicAccessBlock configuration for an Amazon S3 bucket. To use this operation, you must have the s3:PutBucketPublicAccessBlock pe...", Arc::clone(&schema)),
Tool::new("get_bucket_accelerate_configuration", "This operation is not supported for directory buckets. This implementation of the GET action uses the accelerate subresource to return the Transfer Acceleration state of a bucket, which is either E...", Arc::clone(&schema)),
Tool::new("get_bucket_acl", "This operation is not supported for directory buckets. This implementation of the GET action uses the acl subresource to return the access control list (ACL) of a bucket. To use GET to return the A...", Arc::clone(&schema)),
Tool::new("get_bucket_analytics_configuration", "This operation is not supported for directory buckets. This implementation of the GET action returns an analytics configuration (identified by the analytics configuration ID) from the bucket. To us...", Arc::clone(&schema)),
Tool::new("get_bucket_cors", "This operation is not supported for directory buckets. Returns the Cross-Origin Resource Sharing (CORS) configuration information set for the bucket. To use this operation, you must have permission...", Arc::clone(&schema)),
Tool::new("get_bucket_encryption", "Returns the default encryption configuration for an Amazon S3 bucket. By default, all buckets have a default encryption configuration that uses server-side encryption with Amazon S3 managed keys (S...", Arc::clone(&schema)),
Tool::new("get_bucket_intelligent_tiering_configuration", "This operation is not supported for directory buckets. Gets the S3 Intelligent-Tiering configuration from the specified bucket. The S3 Intelligent-Tiering storage class is designed to optimize stor...", Arc::clone(&schema)),
Tool::new("get_bucket_inventory_configuration", "This operation is not supported for directory buckets. Returns an inventory configuration (identified by the inventory configuration ID) from the bucket. To use this operation, you must have permis...", Arc::clone(&schema)),
Tool::new("get_bucket_lifecycle_configuration", "Returns the lifecycle configuration information set on the bucket. For information about lifecycle configuration, see Object Lifecycle Management. Bucket lifecycle configuration now supports specif...", Arc::clone(&schema)),
Tool::new("get_bucket_location", "This operation is not supported for directory buckets. Returns the Region the bucket resides in. You set the bucket's Region using the LocationConstraint request parameter in a CreateBucket request...", Arc::clone(&schema)),
Tool::new("get_bucket_logging", "This operation is not supported for directory buckets. Returns the logging status of a bucket and the permissions users have to view and modify that status. The following operations are related to ...", Arc::clone(&schema)),
Tool::new("get_bucket_metadata_table_configuration", "Retrieves the metadata table configuration for a general purpose bucket. For more information, see Accelerating data discovery with S3 Metadata in the Amazon S3 User Guide. Permissions To use this ...", Arc::clone(&schema)),
Tool::new("get_bucket_metrics_configuration", "This operation is not supported for directory buckets. Gets a metrics configuration (specified by the metrics configuration ID) from the bucket. Note that this doesn't include the daily storage met...", Arc::clone(&schema)),
Tool::new("get_bucket_notification_configuration", "This operation is not supported for directory buckets. Returns the notification configuration of a bucket. If notifications are not enabled on the bucket, the action returns an empty NotificationCo...", Arc::clone(&schema)),
Tool::new("get_bucket_ownership_controls", "This operation is not supported for directory buckets. Retrieves OwnershipControls for an Amazon S3 bucket. To use this operation, you must have the s3:GetBucketOwnershipControls permission. For mo...", Arc::clone(&schema)),
Tool::new("get_bucket_policy", "Returns the policy of a specified bucket. Directory buckets - For directory buckets, you must make requests for this API operation to the Regional endpoint. These endpoints support path-style reque...", Arc::clone(&schema)),
Tool::new("get_bucket_policy_status", "This operation is not supported for directory buckets. Retrieves the policy status for an Amazon S3 bucket, indicating whether the bucket is public. In order to use this operation, you must have th...", Arc::clone(&schema)),
Tool::new("get_bucket_replication", "This operation is not supported for directory buckets. Returns the replication configuration of a bucket. It can take a while to propagate the put or delete a replication configuration to all Amazo...", Arc::clone(&schema)),
Tool::new("get_bucket_request_payment", "This operation is not supported for directory buckets. Returns the request payment configuration of a bucket. To use this version of the operation, you must be the bucket owner. For more informatio...", Arc::clone(&schema)),
Tool::new("get_bucket_tagging", "This operation is not supported for directory buckets. Returns the tag set associated with the bucket. To use this operation, you must have permission to perform the s3:GetBucketTagging action. By ...", Arc::clone(&schema)),
Tool::new("get_bucket_versioning", "This operation is not supported for directory buckets. Returns the versioning state of a bucket. To retrieve the versioning state of a bucket, you must be the bucket owner. This implementation also...", Arc::clone(&schema)),
Tool::new("get_bucket_website", "This operation is not supported for directory buckets. Returns the website configuration for a bucket. To host website on Amazon S3, you can configure a bucket as website by adding a website config...", Arc::clone(&schema)),
Tool::new("get_object", "Retrieves an object from Amazon S3. In the GetObject request, specify the full key name for the object. General purpose buckets - Both the virtual-hosted-style requests and the path-style requests ...", Arc::clone(&schema)),
Tool::new("get_object_acl", "This operation is not supported for directory buckets. Returns the access control list (ACL) of an object. To use this operation, you must have s3:GetObjectAcl permissions or READ_ACP access to the...", Arc::clone(&schema)),
Tool::new("get_object_attributes", "Retrieves all the metadata from an object without returning the object itself. This operation is useful if you're interested only in an object's metadata. GetObjectAttributes combines the functiona...", Arc::clone(&schema)),
Tool::new("get_object_legal_hold", "This operation is not supported for directory buckets. Gets an object's current legal hold status. For more information, see Locking Objects. This functionality is not supported for Amazon S3 on Ou...", Arc::clone(&schema)),
Tool::new("get_object_lock_configuration", "This operation is not supported for directory buckets. Gets the Object Lock configuration for a bucket. The rule specified in the Object Lock configuration will be applied by default to every new o...", Arc::clone(&schema)),
Tool::new("get_object_retention", "This operation is not supported for directory buckets. Retrieves an object's retention settings. For more information, see Locking Objects. This functionality is not supported for Amazon S3 on Outp...", Arc::clone(&schema)),
Tool::new("get_object_tagging", "This operation is not supported for directory buckets. Returns the tag-set of an object. You send the GET request against the tagging subresource associated with the object. To use this operation, ...", Arc::clone(&schema)),
Tool::new("get_object_torrent", "This operation is not supported for directory buckets. Returns torrent files from a bucket. BitTorrent can save you bandwidth when you're distributing large files. You can get torrent only for obje...", Arc::clone(&schema)),
Tool::new("get_public_access_block", "This operation is not supported for directory buckets. Retrieves the PublicAccessBlock configuration for an Amazon S3 bucket. To use this operation, you must have the s3:GetBucketPublicAccessBlock ...", Arc::clone(&schema)),
Tool::new("head_bucket", "You can use this operation to determine if a bucket exists and if you have permission to access it. The action returns a 200 OK if the bucket exists and you have permission to access it. If the buc...", Arc::clone(&schema)),
Tool::new("head_object", "The HEAD operation retrieves metadata from an object without returning the object itself. This operation is useful if you're interested only in an object's metadata. A HEAD request has the same opt...", Arc::clone(&schema)),
Tool::new("list_bucket_analytics_configurations", "This operation is not supported for directory buckets. Lists the analytics configurations for the bucket. You can have up to 1,000 analytics configurations per bucket. This action supports list pag...", Arc::clone(&schema)),
Tool::new("list_bucket_intelligent_tiering_configurations", "This operation is not supported for directory buckets. Lists the S3 Intelligent-Tiering configuration from the specified bucket. The S3 Intelligent-Tiering storage class is designed to optimize sto...", Arc::clone(&schema)),
Tool::new("list_bucket_inventory_configurations", "This operation is not supported for directory buckets. Returns a list of inventory configurations for the bucket. You can have up to 1,000 analytics configurations per bucket. This action supports ...", Arc::clone(&schema)),
Tool::new("list_bucket_metrics_configurations", "This operation is not supported for directory buckets. Lists the metrics configurations for the bucket. The metrics configurations are only for the request metrics of the bucket and do not provide ...", Arc::clone(&schema)),
Tool::new("list_buckets", "This operation is not supported for directory buckets. Returns a list of all buckets owned by the authenticated sender of the request. To grant IAM permission to use this operation, you must add th...", Arc::clone(&schema)),
Tool::new("list_multipart_uploads", "This operation lists in-progress multipart uploads in a bucket. An in-progress multipart upload is a multipart upload that has been initiated by the CreateMultipartUpload request, but has not yet b...", Arc::clone(&schema)),
Tool::new("list_object_versions", "This operation is not supported for directory buckets. Returns metadata about all versions of the objects in a bucket. You can also use request parameters as selection criteria to return metadata a...", Arc::clone(&schema)),
Tool::new("list_objects", "This operation is not supported for directory buckets. Returns some or all (up to 1,000) of the objects in a bucket. You can use the request parameters as selection criteria to return a subset of t...", Arc::clone(&schema)),
Tool::new("list_objects_v2", "Returns some or all (up to 1,000) of the objects in a bucket with each request. You can use the request parameters as selection criteria to return a subset of the objects in a bucket. A 200 OK resp...", Arc::clone(&schema)),
Tool::new("list_parts", "Lists the parts that have been uploaded for a specific multipart upload. To use this operation, you must provide the upload ID in the request. You obtain this uploadID by sending the initiate multi...", Arc::clone(&schema)),
Tool::new("put_bucket_accelerate_configuration", "This operation is not supported for directory buckets. Sets the accelerate configuration of an existing bucket. Amazon S3 Transfer Acceleration is a bucket-level feature that enables you to perform...", Arc::clone(&schema)),
Tool::new("put_bucket_acl", "This operation is not supported for directory buckets. Sets the permissions on an existing bucket using access control lists (ACL). For more information, see Using ACLs. To set the ACL of a bucket,...", Arc::clone(&schema)),
Tool::new("put_bucket_analytics_configuration", "This operation is not supported for directory buckets. Sets an analytics configuration for the bucket (specified by the analytics configuration ID). You can have up to 1,000 analytics configuration...", Arc::clone(&schema)),
Tool::new("put_bucket_cors", "This operation is not supported for directory buckets. Sets the cors configuration for your bucket. If the configuration exists, Amazon S3 replaces it. To use this operation, you must be allowed to...", Arc::clone(&schema)),
Tool::new("put_bucket_encryption", "This operation configures default encryption and Amazon S3 Bucket Keys for an existing bucket. Directory buckets - For directory buckets, you must make requests for this API operation to the Region...", Arc::clone(&schema)),
Tool::new("put_bucket_intelligent_tiering_configuration", "This operation is not supported for directory buckets. Puts a S3 Intelligent-Tiering configuration to the specified bucket. You can have up to 1,000 S3 Intelligent-Tiering configurations per bucket...", Arc::clone(&schema)),
Tool::new("put_bucket_inventory_configuration", "This operation is not supported for directory buckets. This implementation of the PUT action adds an inventory configuration (identified by the inventory ID) to the bucket. You can have up to 1,000...", Arc::clone(&schema)),
Tool::new("put_bucket_lifecycle_configuration", "Creates a new lifecycle configuration for the bucket or replaces an existing lifecycle configuration. Keep in mind that this will overwrite an existing lifecycle configuration, so if you want to re...", Arc::clone(&schema)),
Tool::new("put_bucket_logging", "This operation is not supported for directory buckets. Set the logging parameters for a bucket and to specify permissions for who can view and modify the logging parameters. All logs are saved to b...", Arc::clone(&schema)),
Tool::new("put_bucket_metrics_configuration", "This operation is not supported for directory buckets. Sets a metrics configuration (specified by the metrics configuration ID) for the bucket. You can have up to 1,000 metrics configurations per b...", Arc::clone(&schema)),
Tool::new("put_bucket_notification_configuration", "This operation is not supported for directory buckets. Enables notifications of specified events for a bucket. For more information about event notifications, see Configuring Event Notifications. U...", Arc::clone(&schema)),
Tool::new("put_bucket_ownership_controls", "This operation is not supported for directory buckets. Creates or modifies OwnershipControls for an Amazon S3 bucket. To use this operation, you must have the s3:PutBucketOwnershipControls permissi...", Arc::clone(&schema)),
Tool::new("put_bucket_policy", "Applies an Amazon S3 bucket policy to an Amazon S3 bucket. Directory buckets - For directory buckets, you must make requests for this API operation to the Regional endpoint. These endpoints support...", Arc::clone(&schema)),
Tool::new("put_bucket_replication", "This operation is not supported for directory buckets. Creates a replication configuration or replaces an existing one. For more information, see Replication in the Amazon S3 User Guide. Specify th...", Arc::clone(&schema)),
Tool::new("put_bucket_request_payment", "This operation is not supported for directory buckets. Sets the request payment configuration for a bucket. By default, the bucket owner pays for downloads from the bucket. This configuration param...", Arc::clone(&schema)),
Tool::new("put_bucket_tagging", "This operation is not supported for directory buckets. Sets the tags for a bucket. Use tags to organize your Amazon Web Services bill to reflect your own cost structure. To do this, sign up to get ...", Arc::clone(&schema)),
Tool::new("put_bucket_versioning", "This operation is not supported for directory buckets. When you enable versioning on a bucket for the first time, it might take a short amount of time for the change to be fully propagated. While t...", Arc::clone(&schema)),
Tool::new("put_bucket_website", "This operation is not supported for directory buckets. Sets the configuration of the website that is specified in the website subresource. To configure a bucket as a website, you can add this subre...", Arc::clone(&schema)),
Tool::new("put_object", "Adds an object to a bucket. Amazon S3 never adds partial objects; if you receive a success response, Amazon S3 added the entire object to the bucket. You cannot use PutObject to only update a singl...", Arc::clone(&schema)),
Tool::new("put_object_acl", "This operation is not supported for directory buckets. Uses the acl subresource to set the access control list (ACL) permissions for a new or existing object in an S3 bucket. You must have the WRIT...", Arc::clone(&schema)),
Tool::new("put_object_legal_hold", "This operation is not supported for directory buckets. Applies a legal hold configuration to the specified object. For more information, see Locking Objects. This functionality is not supported for...", Arc::clone(&schema)),
Tool::new("put_object_lock_configuration", "This operation is not supported for directory buckets. Places an Object Lock configuration on the specified bucket. The rule specified in the Object Lock configuration will be applied by default to...", Arc::clone(&schema)),
Tool::new("put_object_retention", "This operation is not supported for directory buckets. Places an Object Retention configuration on an object. For more information, see Locking Objects. Users or accounts require the s3:PutObjectRe...", Arc::clone(&schema)),
Tool::new("put_object_tagging", "This operation is not supported for directory buckets. Sets the supplied tag-set to an object that already exists in a bucket. A tag is a key-value pair. For more information, see Object Tagging. Y...", Arc::clone(&schema)),
Tool::new("put_public_access_block", "This operation is not supported for directory buckets. Creates or modifies the PublicAccessBlock configuration for an Amazon S3 bucket. To use this operation, you must have the s3:PutBucketPublicAc...", Arc::clone(&schema)),
Tool::new("restore_object", "This operation is not supported for directory buckets. Restores an archived copy of an object back into Amazon S3 This functionality is not supported for Amazon S3 on Outposts. This action performs...", Arc::clone(&schema)),
Tool::new("select_object_content", "This operation is not supported for directory buckets. This action filters the contents of an Amazon S3 object based on a simple structured query language (SQL) statement. In the request, along wit...", Arc::clone(&schema)),
Tool::new("upload_part", "Uploads a part in a multipart upload. In this operation, you provide new data as a part of an object in your request. However, you have an option to specify your existing Amazon S3 object as a data...", Arc::clone(&schema)),
Tool::new("upload_part_copy", "Uploads a part by copying data from an existing object as data source. To specify the data source, you add the request header x-amz-copy-source in your request. To specify a byte range, you add the...", Arc::clone(&schema)),
Tool::new("write_get_object_response", "This operation is not supported for directory buckets. Passes transformed objects to a GetObject operation when using Object Lambda access points. For information about Object Lambda access points,...", Arc::clone(&schema)),
]
}

pub async fn dispatch(s3: &dyn S3, name: &str) -> Result<CallToolResult, rmcp::ErrorData> {
match name {
"abort_multipart_upload" => {
let input = AbortMultipartUploadInput::default();
let req = new_request(input);
match s3.abort_multipart_upload(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"complete_multipart_upload" => {
let input = CompleteMultipartUploadInput::default();
let req = new_request(input);
match s3.complete_multipart_upload(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"copy_object" => {
Ok(CallToolResult::error(vec![Content::text("CopyObject requires parameters that are not yet supported".to_string())]))
}
"create_bucket" => {
let input = CreateBucketInput::default();
let req = new_request(input);
match s3.create_bucket(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"create_bucket_metadata_table_configuration" => {
Ok(CallToolResult::error(vec![Content::text("CreateBucketMetadataTableConfiguration requires parameters that are not yet supported".to_string())]))
}
"create_multipart_upload" => {
let input = CreateMultipartUploadInput::default();
let req = new_request(input);
match s3.create_multipart_upload(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket" => {
let input = DeleteBucketInput::default();
let req = new_request(input);
match s3.delete_bucket(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_analytics_configuration" => {
let input = DeleteBucketAnalyticsConfigurationInput::default();
let req = new_request(input);
match s3.delete_bucket_analytics_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_cors" => {
let input = DeleteBucketCorsInput::default();
let req = new_request(input);
match s3.delete_bucket_cors(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_encryption" => {
let input = DeleteBucketEncryptionInput::default();
let req = new_request(input);
match s3.delete_bucket_encryption(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_intelligent_tiering_configuration" => {
let input = DeleteBucketIntelligentTieringConfigurationInput::default();
let req = new_request(input);
match s3.delete_bucket_intelligent_tiering_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_inventory_configuration" => {
let input = DeleteBucketInventoryConfigurationInput::default();
let req = new_request(input);
match s3.delete_bucket_inventory_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_lifecycle" => {
let input = DeleteBucketLifecycleInput::default();
let req = new_request(input);
match s3.delete_bucket_lifecycle(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_metadata_table_configuration" => {
let input = DeleteBucketMetadataTableConfigurationInput::default();
let req = new_request(input);
match s3.delete_bucket_metadata_table_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_metrics_configuration" => {
let input = DeleteBucketMetricsConfigurationInput::default();
let req = new_request(input);
match s3.delete_bucket_metrics_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_ownership_controls" => {
let input = DeleteBucketOwnershipControlsInput::default();
let req = new_request(input);
match s3.delete_bucket_ownership_controls(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_policy" => {
let input = DeleteBucketPolicyInput::default();
let req = new_request(input);
match s3.delete_bucket_policy(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_replication" => {
let input = DeleteBucketReplicationInput::default();
let req = new_request(input);
match s3.delete_bucket_replication(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_tagging" => {
let input = DeleteBucketTaggingInput::default();
let req = new_request(input);
match s3.delete_bucket_tagging(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_bucket_website" => {
let input = DeleteBucketWebsiteInput::default();
let req = new_request(input);
match s3.delete_bucket_website(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_object" => {
let input = DeleteObjectInput::default();
let req = new_request(input);
match s3.delete_object(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_object_tagging" => {
let input = DeleteObjectTaggingInput::default();
let req = new_request(input);
match s3.delete_object_tagging(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"delete_objects" => {
Ok(CallToolResult::error(vec![Content::text("DeleteObjects requires parameters that are not yet supported".to_string())]))
}
"delete_public_access_block" => {
let input = DeletePublicAccessBlockInput::default();
let req = new_request(input);
match s3.delete_public_access_block(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_accelerate_configuration" => {
let input = GetBucketAccelerateConfigurationInput::default();
let req = new_request(input);
match s3.get_bucket_accelerate_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_acl" => {
let input = GetBucketAclInput::default();
let req = new_request(input);
match s3.get_bucket_acl(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_analytics_configuration" => {
let input = GetBucketAnalyticsConfigurationInput::default();
let req = new_request(input);
match s3.get_bucket_analytics_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_cors" => {
let input = GetBucketCorsInput::default();
let req = new_request(input);
match s3.get_bucket_cors(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_encryption" => {
let input = GetBucketEncryptionInput::default();
let req = new_request(input);
match s3.get_bucket_encryption(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_intelligent_tiering_configuration" => {
let input = GetBucketIntelligentTieringConfigurationInput::default();
let req = new_request(input);
match s3.get_bucket_intelligent_tiering_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_inventory_configuration" => {
let input = GetBucketInventoryConfigurationInput::default();
let req = new_request(input);
match s3.get_bucket_inventory_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_lifecycle_configuration" => {
let input = GetBucketLifecycleConfigurationInput::default();
let req = new_request(input);
match s3.get_bucket_lifecycle_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_location" => {
let input = GetBucketLocationInput::default();
let req = new_request(input);
match s3.get_bucket_location(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_logging" => {
let input = GetBucketLoggingInput::default();
let req = new_request(input);
match s3.get_bucket_logging(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_metadata_table_configuration" => {
let input = GetBucketMetadataTableConfigurationInput::default();
let req = new_request(input);
match s3.get_bucket_metadata_table_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_metrics_configuration" => {
let input = GetBucketMetricsConfigurationInput::default();
let req = new_request(input);
match s3.get_bucket_metrics_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_notification_configuration" => {
let input = GetBucketNotificationConfigurationInput::default();
let req = new_request(input);
match s3.get_bucket_notification_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_ownership_controls" => {
let input = GetBucketOwnershipControlsInput::default();
let req = new_request(input);
match s3.get_bucket_ownership_controls(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_policy" => {
let input = GetBucketPolicyInput::default();
let req = new_request(input);
match s3.get_bucket_policy(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_policy_status" => {
let input = GetBucketPolicyStatusInput::default();
let req = new_request(input);
match s3.get_bucket_policy_status(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_replication" => {
let input = GetBucketReplicationInput::default();
let req = new_request(input);
match s3.get_bucket_replication(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_request_payment" => {
let input = GetBucketRequestPaymentInput::default();
let req = new_request(input);
match s3.get_bucket_request_payment(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_tagging" => {
let input = GetBucketTaggingInput::default();
let req = new_request(input);
match s3.get_bucket_tagging(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_versioning" => {
let input = GetBucketVersioningInput::default();
let req = new_request(input);
match s3.get_bucket_versioning(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_bucket_website" => {
let input = GetBucketWebsiteInput::default();
let req = new_request(input);
match s3.get_bucket_website(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_object" => {
let input = GetObjectInput::default();
let req = new_request(input);
match s3.get_object(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_object_acl" => {
let input = GetObjectAclInput::default();
let req = new_request(input);
match s3.get_object_acl(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_object_attributes" => {
let input = GetObjectAttributesInput::default();
let req = new_request(input);
match s3.get_object_attributes(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_object_legal_hold" => {
let input = GetObjectLegalHoldInput::default();
let req = new_request(input);
match s3.get_object_legal_hold(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_object_lock_configuration" => {
let input = GetObjectLockConfigurationInput::default();
let req = new_request(input);
match s3.get_object_lock_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_object_retention" => {
let input = GetObjectRetentionInput::default();
let req = new_request(input);
match s3.get_object_retention(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_object_tagging" => {
let input = GetObjectTaggingInput::default();
let req = new_request(input);
match s3.get_object_tagging(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_object_torrent" => {
let input = GetObjectTorrentInput::default();
let req = new_request(input);
match s3.get_object_torrent(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"get_public_access_block" => {
let input = GetPublicAccessBlockInput::default();
let req = new_request(input);
match s3.get_public_access_block(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"head_bucket" => {
let input = HeadBucketInput::default();
let req = new_request(input);
match s3.head_bucket(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"head_object" => {
let input = HeadObjectInput::default();
let req = new_request(input);
match s3.head_object(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"list_bucket_analytics_configurations" => {
let input = ListBucketAnalyticsConfigurationsInput::default();
let req = new_request(input);
match s3.list_bucket_analytics_configurations(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"list_bucket_intelligent_tiering_configurations" => {
let input = ListBucketIntelligentTieringConfigurationsInput::default();
let req = new_request(input);
match s3.list_bucket_intelligent_tiering_configurations(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"list_bucket_inventory_configurations" => {
let input = ListBucketInventoryConfigurationsInput::default();
let req = new_request(input);
match s3.list_bucket_inventory_configurations(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"list_bucket_metrics_configurations" => {
let input = ListBucketMetricsConfigurationsInput::default();
let req = new_request(input);
match s3.list_bucket_metrics_configurations(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"list_buckets" => {
let input = ListBucketsInput::default();
let req = new_request(input);
match s3.list_buckets(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"list_multipart_uploads" => {
let input = ListMultipartUploadsInput::default();
let req = new_request(input);
match s3.list_multipart_uploads(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"list_object_versions" => {
let input = ListObjectVersionsInput::default();
let req = new_request(input);
match s3.list_object_versions(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"list_objects" => {
let input = ListObjectsInput::default();
let req = new_request(input);
match s3.list_objects(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"list_objects_v2" => {
let input = ListObjectsV2Input::default();
let req = new_request(input);
match s3.list_objects_v2(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"list_parts" => {
let input = ListPartsInput::default();
let req = new_request(input);
match s3.list_parts(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"put_bucket_accelerate_configuration" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketAccelerateConfiguration requires parameters that are not yet supported".to_string())]))
}
"put_bucket_acl" => {
let input = PutBucketAclInput::default();
let req = new_request(input);
match s3.put_bucket_acl(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"put_bucket_analytics_configuration" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketAnalyticsConfiguration requires parameters that are not yet supported".to_string())]))
}
"put_bucket_cors" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketCors requires parameters that are not yet supported".to_string())]))
}
"put_bucket_encryption" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketEncryption requires parameters that are not yet supported".to_string())]))
}
"put_bucket_intelligent_tiering_configuration" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketIntelligentTieringConfiguration requires parameters that are not yet supported".to_string())]))
}
"put_bucket_inventory_configuration" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketInventoryConfiguration requires parameters that are not yet supported".to_string())]))
}
"put_bucket_lifecycle_configuration" => {
let input = PutBucketLifecycleConfigurationInput::default();
let req = new_request(input);
match s3.put_bucket_lifecycle_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"put_bucket_logging" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketLogging requires parameters that are not yet supported".to_string())]))
}
"put_bucket_metrics_configuration" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketMetricsConfiguration requires parameters that are not yet supported".to_string())]))
}
"put_bucket_notification_configuration" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketNotificationConfiguration requires parameters that are not yet supported".to_string())]))
}
"put_bucket_ownership_controls" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketOwnershipControls requires parameters that are not yet supported".to_string())]))
}
"put_bucket_policy" => {
let input = PutBucketPolicyInput::default();
let req = new_request(input);
match s3.put_bucket_policy(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"put_bucket_replication" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketReplication requires parameters that are not yet supported".to_string())]))
}
"put_bucket_request_payment" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketRequestPayment requires parameters that are not yet supported".to_string())]))
}
"put_bucket_tagging" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketTagging requires parameters that are not yet supported".to_string())]))
}
"put_bucket_versioning" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketVersioning requires parameters that are not yet supported".to_string())]))
}
"put_bucket_website" => {
Ok(CallToolResult::error(vec![Content::text("PutBucketWebsite requires parameters that are not yet supported".to_string())]))
}
"put_object" => {
let input = PutObjectInput::default();
let req = new_request(input);
match s3.put_object(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"put_object_acl" => {
let input = PutObjectAclInput::default();
let req = new_request(input);
match s3.put_object_acl(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"put_object_legal_hold" => {
let input = PutObjectLegalHoldInput::default();
let req = new_request(input);
match s3.put_object_legal_hold(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"put_object_lock_configuration" => {
let input = PutObjectLockConfigurationInput::default();
let req = new_request(input);
match s3.put_object_lock_configuration(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"put_object_retention" => {
let input = PutObjectRetentionInput::default();
let req = new_request(input);
match s3.put_object_retention(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"put_object_tagging" => {
Ok(CallToolResult::error(vec![Content::text("PutObjectTagging requires parameters that are not yet supported".to_string())]))
}
"put_public_access_block" => {
Ok(CallToolResult::error(vec![Content::text("PutPublicAccessBlock requires parameters that are not yet supported".to_string())]))
}
"restore_object" => {
let input = RestoreObjectInput::default();
let req = new_request(input);
match s3.restore_object(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"select_object_content" => {
Ok(CallToolResult::error(vec![Content::text("SelectObjectContent requires parameters that are not yet supported".to_string())]))
}
"upload_part" => {
let input = UploadPartInput::default();
let req = new_request(input);
match s3.upload_part(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
"upload_part_copy" => {
Ok(CallToolResult::error(vec![Content::text("UploadPartCopy requires parameters that are not yet supported".to_string())]))
}
"write_get_object_response" => {
let input = WriteGetObjectResponseInput::default();
let req = new_request(input);
match s3.write_get_object_response(req).await {
Ok(resp) => Ok(CallToolResult::success(vec![Content::text(format!("{:#?}", resp.output))])),
Err(e) => Ok(CallToolResult::error(vec![Content::text(format!("S3 error: {e}"))])),
}
}
_ => Err(rmcp::ErrorData::invalid_params(format!("unknown tool: {name}"), None)),
}
}
