// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2023-2026 The s3s Authors

//! Generated test-suite codegen: emits `crates/s3s/tests/generated/`, a single
//! integration-test binary whose module tree and cases are regenerated from the
//! Smithy models, so the test families stay in sync with the generated API.
//!
//! The directory is compiled as one test target declared in `crates/s3s/Cargo.toml`.
//! cargo-llvm-cov ignores `tests/` directories by default, so the generated test
//! bodies stay out of the coverage denominator while the production lines they
//! execute still count towards the numerator.

mod debug;
mod dto;
mod ops;
mod xml;

use super::dto::RustTypes;
use super::ops::Operations;
use super::write_dir_file;

use scoped_writer::g;

/// Directory (relative to the repository root) holding the generated test binary.
pub(super) const GENERATED_TESTS_DIR: &str = "crates/s3s/tests/generated";

/// Files of the generated test binary: the module loader first, then one file
/// per test family. The set is fixed, so a codegen run never leaves a stale file
/// behind.
const TEST_MODULES: &[&str] = &["debug", "dto", "ops", "xml"];

/// Emits the generated test binary: the module loader plus one file per family.
///
/// `gen_tests` receives the union (`minio`) model and the base model. The union
/// is a superset, so a reference to a type that the base model does not describe
/// must be gated with `#[cfg(feature = "minio")]`; `is_minio_only` answers that
/// question for the emitters.
pub(super) fn codegen(ops: &Operations, rust_types_base: &RustTypes, rust_types_minio: &RustTypes) {
    write_test_file("main.rs", || {
        codegen_file_header(None);
        for module in TEST_MODULES {
            g!("mod {module};");
        }
        g!();
    });

    debug::codegen(ops, rust_types_base, rust_types_minio);
    dto::codegen(ops, rust_types_base, rust_types_minio);
    ops::codegen(ops, rust_types_base, rust_types_minio);
    xml::codegen(ops, rust_types_base, rust_types_minio);
}

/// Writes the repository-standard header plus the `//! Auto generated by`
/// marker naming the emitter: `gen_tests::<family>::codegen`, or
/// `gen_tests::codegen` for the module loader itself (`family` is `None`).
pub(super) fn codegen_file_header(family: Option<&str>) {
    let base = module_path!();
    let emitter = match family {
        Some(family) => format!("{base}::{family}::codegen"),
        None => format!("{base}::codegen"),
    };
    g!("// SPDX-License-Identifier: Apache-2.0");
    g!("// SPDX-FileCopyrightText: 2023-2026 The s3s Authors");
    g!();
    g!("//! Auto generated by `{emitter}`");
    g!();
}

/// Writes one file of the generated test binary.
pub(super) fn write_test_file(name: &str, f: impl FnOnce()) {
    write_dir_file(GENERATED_TESTS_DIR, name, f);
}

/// Whether `name` only exists in the union (`minio`) model.
///
/// Every reference to such a type must be gated with
/// `#[cfg(feature = "minio")]`, mirroring the gate that the merged
/// `generated.rs` puts on the item itself.
pub(super) fn is_minio_only(name: &str, rust_types_base: &RustTypes, rust_types_minio: &RustTypes) -> bool {
    rust_types_minio.contains_key(name) && !rust_types_base.contains_key(name)
}
