#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2023-2026 Nugine

"""Check or add SPDX license headers to original source files.

Comment prefix is chosen by extension: `//` for Rust, `#` for Python and shell.
Generated files (marked with `//! Auto generated by`) are owned by
`s3s-codegen`: `--check` still verifies their headers, but `--apply` skips them.

Usage:
    python scripts/spdx_headers.py --check   # verify, exit 1 on failure
    python scripts/spdx_headers.py --apply   # insert missing headers in place
"""

import argparse
import sys
from pathlib import Path

SPDX_LINES = [
    "SPDX-License-Identifier: Apache-2.0",
    "SPDX-FileCopyrightText: 2023-2026 Nugine",
]

COMMENT_PREFIX = {".rs": "//", ".py": "#", ".sh": "#"}

EXTENSIONS = set(COMMENT_PREFIX)
EXCLUDED_DIRS = {
    "target",
    ".venv",
    ".git",
    ".cache",
    ".idea",
    ".vscode",
    "node_modules",
}
GENERATED_MARKER = "//! Auto generated by"

ROOT = Path(__file__).parent.parent


def iter_targets():
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file() or path.suffix not in EXTENSIONS:
            continue
        parts = set(path.relative_to(ROOT).parts[:-1])
        if parts & EXCLUDED_DIRS:
            continue
        yield path


def header_lines(suffix: str):
    prefix = COMMENT_PREFIX[suffix]
    return [f"{prefix} {line}" for line in SPDX_LINES]


def is_generated(text: str) -> bool:
    head = "\n".join(text.splitlines()[:10])
    return any(line.lstrip().startswith(GENERATED_MARKER) for line in head.splitlines())


def insert_header(text: str, suffix: str) -> str:
    header = "\n".join(header_lines(suffix))
    lines = text.splitlines(keepends=True)
    if suffix != ".rs" and lines and lines[0].startswith("#!"):
        shebang = lines[0]
        rest = "".join(lines[1:])
        return f"{shebang}{header}\n\n{rest.lstrip('\n')}"
    return f"{header}\n\n{text.lstrip('\n')}"


def has_header(text: str, suffix: str) -> bool:
    body = text
    if suffix != ".rs" and body.startswith("#!"):
        _, _, body = body.partition("\n")
    return all(line in body.splitlines()[:4] for line in header_lines(suffix))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--check", action="store_true", help="verify headers, exit 1 on failure"
    )
    mode.add_argument("--apply", action="store_true", help="insert missing headers")
    args = parser.parse_args()

    failures = []
    applied = skipped_generated = 0
    for path in iter_targets():
        text = path.read_text(encoding="utf-8")
        suffix = path.suffix
        if has_header(text, suffix):
            continue
        generated = is_generated(text)
        if args.apply:
            if generated:
                skipped_generated += 1
                continue
            path.write_text(insert_header(text, suffix), encoding="utf-8")
            applied += 1
        else:
            failures.append(
                f"{path.relative_to(ROOT)}{' (generated)' if generated else ''}"
            )

    if args.apply:
        print(
            f"applied: {applied} file(s), skipped generated: {skipped_generated} file(s)"
        )
        return 0
    if failures:
        print(f"missing SPDX header in {len(failures)} file(s):")
        print("\n".join(failures))
        return 1
    print("all source files carry the SPDX header")
    return 0


if __name__ == "__main__":
    sys.exit(main())
