// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2023-2026 The s3s Authors

//! Check or insert the SPDX license headers of original source files.
//!
//! The comment prefix is chosen by extension: `//` for Rust, `#` for Python and
//! shell. Files marked with `//! Auto generated by` are owned by `s3s-codegen`:
//! `--check` still verifies their headers, `--apply` skips them.

use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::{ArgGroup, Parser};

use crate::repo_root;

const SPDX_LINES: [&str; 2] = [
    "SPDX-License-Identifier: Apache-2.0",
    "SPDX-FileCopyrightText: 2023-2026 The s3s Authors",
];

const EXCLUDED_DIRS: [&str; 7] = ["target", ".venv", ".git", ".cache", ".idea", ".vscode", "node_modules"];

const GENERATED_MARKER: &str = "//! Auto generated by";

/// Check or insert SPDX license headers.
#[derive(Debug, Parser)]
#[command(group(ArgGroup::new("mode").required(true).args(["check", "apply"])))]
pub(crate) struct Spdx {
    /// Verify that every source file carries the header.
    #[arg(long)]
    check: bool,

    /// Insert the header into the files that miss it.
    #[arg(long)]
    apply: bool,
}

/// Which of the two modes the caller selected.
///
/// The clap group on the struct requires exactly one of the two flags, so the
/// command line never reaches the empty or the ambiguous case; both are kept as
/// a guard for programmatic callers and are covered by the unit test below.
#[derive(Debug, PartialEq, Eq)]
enum Mode {
    Check,
    Apply,
}

impl Spdx {
    pub(crate) fn run(self) -> Result<bool> {
        let mode = self.mode()?;
        let root = repo_root();
        let mut files = Vec::new();
        collect(&root, &mut files)?;

        let mut failures = Vec::new();
        let mut applied = 0_usize;
        let mut skipped_generated = 0_usize;

        for path in files {
            let text = fs::read_to_string(&path).with_context(|| format!("failed to read {}", path.display()))?;
            let Some(prefix) = path.extension().and_then(OsStr::to_str).and_then(comment_prefix) else {
                continue;
            };
            if has_header(&text, prefix) {
                continue;
            }
            let generated = is_generated(&text);
            if mode == Mode::Apply {
                if generated {
                    skipped_generated += 1;
                    continue;
                }
                fs::write(&path, insert_header(&text, prefix)).with_context(|| format!("failed to write {}", path.display()))?;
                applied += 1;
            } else {
                let relative = path.strip_prefix(&root).unwrap_or(&path).display();
                let marker = if generated { " (generated)" } else { "" };
                failures.push(format!("{relative}{marker}"));
            }
        }

        if mode == Mode::Apply {
            println!("applied: {applied} file(s), skipped generated: {skipped_generated} file(s)");
            return Ok(true);
        }
        if failures.is_empty() {
            println!("all source files carry the SPDX header");
            return Ok(true);
        }
        println!("missing SPDX header in {} file(s):", failures.len());
        println!("{}", failures.join("\n"));
        Ok(false)
    }

    /// Read both flags instead of inferring the mode from `--apply`.
    fn mode(&self) -> Result<Mode> {
        match (self.check, self.apply) {
            (true, false) => Ok(Mode::Check),
            (false, true) => Ok(Mode::Apply),
            (false, false) => bail!("no mode selected: pass --check or --apply"),
            (true, true) => bail!("--check and --apply are mutually exclusive"),
        }
    }
}

fn comment_prefix(extension: &str) -> Option<&'static str> {
    match extension {
        "rs" => Some("//"),
        "py" | "sh" => Some("#"),
        _ => None,
    }
}

fn header_lines(prefix: &str) -> [String; 2] {
    SPDX_LINES.map(|line| format!("{prefix} {line}"))
}

fn has_header(text: &str, prefix: &str) -> bool {
    let body = if prefix == "#" && text.starts_with("#!") {
        text.split_once('\n').map_or("", |(_, rest)| rest)
    } else {
        text
    };
    header_lines(prefix)
        .iter()
        .all(|header| body.lines().take(4).any(|line| line == header))
}

fn is_generated(text: &str) -> bool {
    text.lines()
        .take(10)
        .any(|line| line.trim_start().starts_with(GENERATED_MARKER))
}

fn insert_header(text: &str, prefix: &str) -> String {
    let header = header_lines(prefix).join("\n");
    if prefix == "#"
        && let Some((shebang, rest)) = text.split_once('\n')
        && shebang.starts_with("#!")
    {
        return format!("{shebang}\n{header}\n\n{}", rest.trim_start_matches('\n'));
    }
    format!("{header}\n\n{}", text.trim_start_matches('\n'))
}

fn collect(dir: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    let mut entries = fs::read_dir(dir)
        .with_context(|| format!("failed to read {}", dir.display()))?
        .collect::<Result<Vec<_>, _>>()
        .with_context(|| format!("failed to read {}", dir.display()))?;
    entries.sort_by_key(fs::DirEntry::path);

    for entry in entries {
        let path = entry.path();
        if entry
            .file_type()
            .with_context(|| format!("failed to stat {}", path.display()))?
            .is_dir()
        {
            let excluded = path
                .file_name()
                .and_then(OsStr::to_str)
                .is_some_and(|name| EXCLUDED_DIRS.contains(&name));
            if !excluded {
                collect(&path, files)?;
            }
        } else if path
            .extension()
            .and_then(OsStr::to_str)
            .is_some_and(|ext| comment_prefix(ext).is_some())
        {
            files.push(path);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{Mode, Spdx};

    fn spdx(check: bool, apply: bool) -> Spdx {
        Spdx { check, apply }
    }

    #[test]
    fn mode_reads_both_flags() {
        assert_eq!(spdx(true, false).mode().unwrap(), Mode::Check);
        assert_eq!(spdx(false, true).mode().unwrap(), Mode::Apply);
    }

    #[test]
    fn mode_rejects_an_empty_or_ambiguous_selection() {
        assert!(spdx(false, false).mode().is_err());
        assert!(spdx(true, true).mode().is_err());
    }
}
