[package]
name = "s3s-sigv4"
version = "0.16.0-alpha.1"
description = "AWS Signature Version 4: parsing, canonicalization, and signing"
readme = "../../README.md"
keywords = ["s3", "aws", "signature", "sigv4"]
categories = ["cryptography", "web-programming"]
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
arrayvec.workspace = true
jiff.workspace = true
nom.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
