[package]
name = "s3s-chunked"
version = "0.18.0-alpha.1"
description = "Async streaming decoder for aws-chunked request bodies"
readme = "../../README.md"
keywords = ["aws", "chunked", "streaming", "parser", "s3"]
categories = ["web-programming", "asynchronous"]
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
bytes.workspace = true
futures-core.workspace = true
http.workspace = true
memchr.workspace = true
pin-project-lite.workspace = true
s3s-sigv4.workspace = true
sha2.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
futures = { workspace = true, features = ["executor"] }
